# Generated by Django 6.0.3 on 2026-04-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('image_list', models.JSONField(blank=True, default=list)),
                ('vector', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Địa danh',
                'verbose_name_plural': 'Danh sách địa danh',
                'db_table': 'points_of_interest',
            },
        ),
    ]
