# Generated by Django 6.0.3 on 2026-05-04 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VibeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('khong_gian', '🌿 Không gian'), ('am_thuc', '🍜 Ẩm thực'), ('van_hoa', '🏛️ Văn hóa & Lịch sử'), ('hoat_dong', '🏃 Hoạt động'), ('thoi_gian', '🕐 Thời điểm')], max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('prompt_keyword', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Thẻ Vibe',
                'ordering': ['category', 'label'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('vibes', models.ManyToManyField(blank=True, to='api.vibetag')),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
            },
        ),
    ]
