# Generated by Django 6.0.3 on 2026-05-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sharedroute'),
        ('api', '0002_vibetag_userprofile'),
    ]

    operations = [
    ]
