# Generated by Django 6.0.3 on 2026-05-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pointofinterest_text_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='user_ratings_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
