# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pointofinterest_rating_and_more'),
        ('api', '0006_remove_userprofile_birth_year_userprofile_birth_date'),
    ]

    operations = [
    ]
